// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtrycNpx3my82f4PR1LibaXRhvq5gj1nU',
    appId: '1:416173972105:web:e28537cf44caee2547c458',
    messagingSenderId: '416173972105',
    projectId: 'openapp-71a9b',
    authDomain: 'openapp-71a9b.firebaseapp.com',
    storageBucket: 'openapp-71a9b.appspot.com',
    measurementId: 'G-MFGJR8SGFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqOUSPsFNnspyqItFqfy4BjqcVF8q6O4',
    appId: '1:416173972105:android:1022a92f9cf9196447c458',
    messagingSenderId: '416173972105',
    projectId: 'openapp-71a9b',
    storageBucket: 'openapp-71a9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_2jkEcD_rM_iealoZVUk8Kj3bPA0FTRM',
    appId: '1:416173972105:ios:551fcead97b6c18b47c458',
    messagingSenderId: '416173972105',
    projectId: 'openapp-71a9b',
    storageBucket: 'openapp-71a9b.appspot.com',
    iosClientId: '416173972105-89vn43ivj646lm14evq031643ebkp3j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedex',
  );
}
